### ISSUE TITLE
[Question] dependencies

### ISSUE THREAD

**Issue by zjin-lcf** [UCL-CCS/HemePure-GPU#5]
Is it feasible to have a HemePure-GPU application without building/using any dependencies ?

**Comment by izacharo** [comment]
Hi, No you need to build the dependencies before compiling the source code. Is there any problem with building the dependencies? Best, Ioannis Sent from my phone-------- Original message --------From: zjin-lcf ***@***.***>Date: Tue, 6 Dec 2022, 23:32To: UCL-CCS/HemePure-GPU ***@***.***>Cc: Subscribed ***@***.***>Subject: [UCL-CCS/HemePure-GPU] [Question] dependencies (Issue #5)
Is it feasible to have a HemePure-GPU application without building/using any dependencies ?
